name: pos
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  badges: ^3.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  client_repository:
    git:
      url: https://github.com/clover-leaf/pos_client_repository.git
      ref: master
  collection: ^1.17.0
  elegant_notification: ^1.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  pos_server:
    git:
      url: https://github.com/clover-leaf/pos_server.git
      ref: master
  shared_preferences: ^2.0.18
  simple_gradient_text: ^1.2.4
  web_socket_client: ^0.1.0-dev.2
  window_manager: ^0.3.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/color.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Extralight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900